apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: my-mongo-app
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 30001
  selector:
    app: mongo-express
  type: LoadBalancer
