apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb  # name of the Pods (spec.template.metadata.labels.app)
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
